---
  - name: Install "express-gateway"
    npm:
      name: express-gateway
      path: /vagrant
      global: true

  - name: Copy gateway files to server
    copy:
      src: "{{ role_path }}/files/gateway"
      dest: $PWD

  - name: Copy gateway config
    template:
      src: gateway.config.yml.j2
      dest: "{{ gateway_config_path }}/gateway.config.yml"

  - name: Copy system config
    template:
      src: system.config.yml.j2
      dest: "{{ gateway_config_path }}/system.config.yml"

  - name: Install "forever"
    npm:
      name: forever
      global: yes

  - name: Check list of Node.js apps running.
    command: forever list
    register: forever_list
    changed_when: false
