---
  - name: Install "express-gateway"
    npm:
      name: express-gateway
      path: /vagrant
      global: true

  - name: Install "forever"
    npm:
      name: forever
      global: yes

  - name: Check list of Node.js apps running.
    command: forever list
    register: forever_list
    changed_when: false
