---
  - name: Install "express-gateway"
    npm:
      name: express-gateway
      path: /vagrant
      global: true

  - name: Copy gateway files to server
    copy:
      src: "{{ role_path }}/files/gateway"
      dest: /opt
    register: gateway_files

  - name: Copy gateway config
    template:
      src: gateway.config.yml.j2
      dest: "{{ gateway_config_path }}/gateway.config.yml"
    register: gateway_config

  - name: Copy system config
    template:
      src: system.config.yml.j2
      dest: "{{ gateway_config_path }}/system.config.yml"

  - name: Install gateway-express dependencies
    shell: npm install --unsafe-perm
    args:
      chdir: "{{ gateway_path }}"
    when: gateway_files.changed

  - name: Copy service file
    template:
      src: gateway.service.j2
      dest: /etc/systemd/system/gateway.service
    register: gateway_service

  - name: Start and enable gateway server
    systemd:
      name: gateway
      state: started
      enabled: yes

  - name: Restart gateway service
    systemd:
      name: gateway
      state: restarted
    when: gateway_config.changed
