---
  - name: Install "express-gateway"
    npm:
      name: express-gateway
      path: /vagrant
      global: true

  - name: Copy gateway files to server
    copy:
      src: "{{ role_path }}/files/gateway"
      dest: /opt

  - name: Copy gateway config
    template:
      src: gateway.config.yml.j2
      dest: "{{ gateway_config_path }}/gateway.config.yml"

  - name: Copy system config
    template:
      src: system.config.yml.j2
      dest: "{{ gateway_config_path }}/system.config.yml"

  - name: Install gateway-express dependencies
    shell: npm install --unsafe-perm
    args:
      chdir: "{{ gateway_path }}"

  - name: Copy service file
    template:
      src: gateway.service.j2
      dest: /etc/systemd/system/gateway.service

  - name: Start and enable gateway server
    systemd:
      name: gateway
      state: started
      enabled: yes


  - name: Install "forever"
    npm:
      name: forever
      global: yes

  - name: Start Gateway
    shell: forever start -c "npm start"
    args:
      chdir: "{{ gateway_path }}"

  - name: Check list of Node.js apps running.
    command: forever list
    register: forever_list
    changed_when: false
