---
  - name: Create postgresbackup directory
    file:
      path: /opt/postgresbackup
      state: directory

  - name: Copy .pgpass file
    template:
      src: .pgpass.j2
      dest: /root/.pgpass
      mode: 0600

  - name: Copy postgresbackup.sh
    template:
      src: postgresbackup.sh.j2
      dest: /opt/postgresbackup/postgresbackup.sh
      mode: 0777

  - name: Set cron job
    cron:
      name: postgres backup
      special_time: daily
      job: bash /opt/postgresbackup/postgresbackup.sh
