---
- name: Installing haproxy
  apt:
    name: haproxy
    state: present

- name: Start haproxy
  systemd:
    name: haproxy
    state: started
    enabled: yes

- name: Transfer haproxy configuration
  template: src={{ role_path }}/templates/{{ inventory_hostname }}.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify: Restart haproxy
