version: '2'
services:
    app:
        build: .
        links:
            - redis
            - mongo
        ports:
            - "8080:8080"
        volumes:
            - .:/opt/app
    redis:
        image: redis:latest
        expose:
            - "6379"
        volumes:
            - ./cache:/var/lib/redis/data
    mongo:
        image: mongo:latest
        expose:
            - "27017"
        volumes:
            - ./db:/var/lib/mongodb
