---
- hosts: mgmt
  tasks:
    - name: generate SSH key-pair
      shell: ssh-keygen -b 2048 -t rsa -f /home/vagrant/.ssh/id_rsa -q -N ""

- hosts: all
  tasks:
    - name: distribute public key
      authorized_key: user=vagrant
                      key="{{ lookup('file', '/home/vagrant/.ssh/id_rsa.pub') }}"
                      state=present
