#!/bin/bash

apt-get update
apt-get -y upgrade
apt-get -y remove ruby

apt-get -y install git-core curl build-essential gcc libssl-dev libreadline-dev \
    postgresql libpq-dev memcached nodejs npm firefox qt5-default \
    libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x
