# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/yakkety64"
    config.vm.network :forwarded_port, guest: 8080, host: 8080

    config.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 2
    end

    config.vm.provision :shell, path: "os_bootstrap"
    config.vm.provision :shell, privileged: false, path: "user_bootstrap"
    config.vm.provision :shell, privileged: false, path: "rbenv_install"
    config.vm.provision :shell, privileged: false, path: "ruby_install"
    config.vm.provision :shell, privileged: false, path: "hours_setup"
    config.vm.provision :shell, run: 'always', privileged: false, inline: <<-SHELL
        cd hours ; bundle exec unicorn -c config/unicorn.rb
    SHELL
end
