---
- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Add jenkins user to docker group
  user:
    name: jenkins
    groups: docker
    append: yes