---
  - name: Ensure that https transport is ready
    apt: 
      name: apt-transport-https 
      state: present

  - name: Ensure the Sensu APT repo GPG key is present
    apt_key:
      url: http://repositories.sensuapp.org/apt/pubkey.gpg
      state: present

  - name: Ensure the Sensu Core APT repo is present
    apt_repository:
      repo: "deb     http://repositories.sensuapp.org/apt {{ ansible_distribution_release }} main"
      state: present
      update_cache: true

  - name: Ensure Sensu is installed
    apt: name=sensu state=present

  - name: Ensure the Sensu config directory is present
    file:
      dest: /etc/sensu/conf.d
      state: directory
      owner: sensu
      group: sensu

  - name: Deploy Sensu RabbitMQ configuration
    template:
      dest: /etc/sensu/conf.d/rabbitmq.json
      owner: sensu
      group: sensu
      src: sensu-rabbitmq.json.j2
    notify:
      - restart sensu-server service
      - restart sensu-api service
      - restart sensu-client service

  - name: Deploy Sensu transport configuration
    template:
      dest: /etc/sensu/conf.d/transport.json
      owner: sensu
      group: sensu
      src: transport.json.j2
    notify:
      - restart sensu-server service
      - restart sensu-api service
      - restart sensu-client service


  - name: Deploy Sensu client service configuration
    template:
      dest: /etc/sensu/conf.d/client.json
      owner: sensu
      group: sensu
      src: client.json.j2
    notify: restart sensu-client service

  - name: Ensure Sensu client service is running
    service:
      name: sensu-client
      state: started
      enabled: yes