# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/yakkety64"
    #config.vm.network :forwarded_port, guest: 30000, host: 3000

    config.vm.provision :shell, inline: <<-SHELL
        apt-get update
        apt-get -y upgrade

        apt-get -y remove ruby

        # Installing core dependencies
        apt-get -y install git-core curl build-essential gcc libssl-dev libreadline-dev
        #apt-get -y install zliblg-dev

        # Installing dependencies for rvm
        apt-get -y install libgdbm-dev libncurses5-dev automake libtool bison libffi-dev

        # installing dependencies for Hours
        apt-get -y install postgresql libpq-dev memcached
        apt-get -y install qt5-default libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x nodejs
    SHELL




    config.vm.provision :shell, privileged: false, inline: <<-SHELL
        sudo -u postgres createuser --superuser ubuntu
        sudo -u postgres createdb ubuntu
    SHELL




    config.vm.provision :shell, privileged: false, inline: <<-SHELL
        git clone https://github.com/rbenv/rbenv.git ~/.rbenv
        git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build

        RBENV_PATH='export PATH="$HOME/.rbenv/bin:$PATH"'
        echo $RBENV_PATH >> ~/.bash_profile
        RBENV_INIT='eval "$(rbenv init -)"'
        echo $RBENV_INIT >> ~/.bash_profile
    SHELL

    config.vm.provision :shell, privileged: false, inline: <<-SHELL
        rbenv install 2.3.1
        rbenv global 2.3.1
    SHELL

    config.vm.provision :shell, privileged: false, inline: <<-SHELL
        gem install bundler
    SHELL



    config.vm.provision :shell, privileged: false, inline: <<-SHELL
        cd /vagrant
        rm -rf Hours
        git clone https://github.com/DefactoSoftware/Hours.git
        cd Hours
        #bundle install
        ./bin/setup
        #foreman start
    SHELL
end
