# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/yakkety64"
    config.vm.network :forwarded_port, guest: 80, host: 80

    config.vm.provision :shell, inline: <<-SHELL
        apt-get update
        apt-get -y upgrade

        apt-get -y remove ruby

        echo 'Installing core dependencies'
        apt-get -y install git-core curl build-essential gcc libssl-dev libreadline-dev

        echo 'Installing dependencies for rvm'
        apt-get -y install libgdbm-dev libncurses5-dev automake libtool bison libffi-dev

        echo 'Installing dependencies for Hours'
        apt-get -y install postgresql libpq-dev memcached
        apt-get -y install qt5-default libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x
        apt-get -y install nodejs npm
    SHELL

    # Adding ubuntu user and databse to Postgres
    config.vm.provision :shell, privileged: false, inline: <<-SHELL
        echo 'Adding ubuntu user and databse to Postgres'
        sudo -u postgres createuser --superuser ubuntu
        sudo -u postgres createdb ubuntu
    SHELL




    # Installing rbenv
    config.vm.provision :shell, privileged: false, inline: <<-SHELL
        echo 'Installing Rbenv'
        git clone https://github.com/rbenv/rbenv.git ~/.rbenv
        git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build

        RBENV_PATH='export PATH="$HOME/.rbenv/bin:$PATH"'
        echo $RBENV_PATH >> ~/.bash_profile
        RBENV_INIT='eval "$(rbenv init -)"'
        echo $RBENV_INIT >> ~/.bash_profile
    SHELL

    # Installing Ruby 2.3.1
    config.vm.provision :shell, privileged: false, inline: <<-SHELL
        echo 'Installing Ruby 2.3.1'
        rbenv install 2.3.1
        rbenv global 2.3.1
    SHELL

    # Installing Bundler
    config.vm.provision :shell, privileged: false, inline: <<-SHELL
        echo 'Installing Bundler'
        gem install bundler
    SHELL




    # Setting up Hours
    config.vm.provision :shell, privileged: false, inline: <<-SHELL
        echo 'Installing Hours'
        rm -rf /vagrant/hours
        git clone https://github.com/DefactoSoftware/Hours.git /vagrant/hours

        cd /vagrant/hours
        ./bin/setup
    SHELL




    config.vm.provision :shell, privileged: false, inline: <<-SHELL
        wget https://github.com/ysbaddaden/prax.cr/releases/download/v0.6.0/prax_0.6.0-1_amd64.deb
        sudo dpkg -i prax_0.6.0-1_amd64.deb
        mkdir ~/.prax

        cd /vagrant/hours
        prax link
    SHELL

    config.vm.provision :shell, privileged: false, inline: <<-SHELL
        prax start &

        cd /vagrant/hours
        foreman start &
    SHELL
end
