---
  - name: Get git checkout
    git:
      repo: 'https://github.com/acme-config-management/client.git'
      dest: "{{ install_path }}"
      force: yes

  - name: Copy service file
    template:
      src: client.service.j2
      dest: /etc/systemd/system/client.service

  - name: Copy .env file
    template:
      src: .env.j2
      dest: "{{ install_path }}/.env"

  - name: Install dependencies
    shell: npm install
    args:
      chdir: "{{ install_path }}"

  - name: Restart the service
    systemd:
      name: client
      state: restarted
      enabled: yes
