version: '2'
services:
    db:
        build: db
        volumes:
            - ./db/backups:/var/lib/postgresql/data
    hours:
        build: hours
        env_file:
            - hours/.env
        links:
            - db:postgres
            - cache:cache
    proxy:
        build: proxy
        ports:
            - "80:80"
            - "443:443"
        links:
            - hours
    cache:
        build: cache
        volumes:
            - ./cache/cache:/data
