version: '2'

services:
    app:
        build: ./app
        env_file: ./app/.hours.env
        links:
            - db:postgres
        ports:
            - "8080:8080"

    db:
        build: ./db
    cache:
        build: ./cache
