---
  - name: Ensure that https transport is ready
    apt: 
      name: apt-transport-https 
      state: present

  - name: Ensure the Sensu APT repo GPG key is present
    apt_key:
      url: http://repositories.sensuapp.org/apt/pubkey.gpg
      state: present

  - name: Ensure the Sensu Core APT repo is present
    apt_repository:
      repo: "deb     http://repositories.sensuapp.org/apt {{ ansible_distribution_release }} main"
      state: present
      update_cache: true

  - name: Ensure Sensu is installed
    apt: name=sensu state=present

  - name: Install Redis  
    apt:
      name: redis-server
      update_cache: yes

  - service:
      name: redis-server
      state: started
  
  - name: Install RabbitMQ prerequisite.
    apt:
      name: erlang-nox
      update_cache: yes

  - name: Install RabbitMQ
    apt:
      name: rabbitmq-server
      update_cache: yes

  - service:
      name: rabbitmq-server
      state: started

  - name: Ensure Sensu RabbitMQ vhost exists
    rabbitmq_vhost: name=/sensu state=present

  - name: Ensure Sensu RabbitMQ user has access to the Sensu vhost
    rabbitmq_user:
      user: sensu
      password: secret
      vhost: /sensu
      configure_priv: .*
      read_priv: .*
      write_priv: .*
      state: present
    become: true
    become_user: rabbitmq
    notify: restart rabbitmq service

  - name: Install Uchiwa
    apt:
      name: uchiwa
      state: present

  - name: Deploy Uchiwa config
    template:
      src: uchiwa_config.json.j2
      dest: /etc/sensu/uchiwa.json
    notify: restart uchiwa service

  - name: Ensure the Sensu config directory is present
    file:
      dest: etc/sensu/conf.d
      state: directory

  - name: Deploy Sensu Redis configuration
    template:
      dest: /etc/sensu/conf.d/redis.json
      owner: sensu
      group: sensu
      src: sensu-redis.json.j2
    notify:
      - restart sensu-server service
      - restart sensu-api service
      - restart sensu-client service

  - name: Deploy Sensu RabbitMQ configuration
    template:
      dest: /etc/sensu/conf.d/rabbitmq.json
      owner: sensu
      group: sensu
      src: sensu-rabbitmq.json.j2
    notify:
      - restart sensu-server service
      - restart sensu-api service
      - restart sensu-client service

  - name: Deploy Sensu transport configuration
    template:
      dest: /etc/sensu/conf.d/transport.json
      owner: sensu
      group: sensu
      src: transport.json.j2
    notify:
      - restart sensu-server service
      - restart sensu-api service
      - restart sensu-client service

  - name: Ensure Uchiwa Dashboard server service is running
    service:
      name: uchiwa
      state: started
      enabled: yes

  - name: Deploy Sensu server API configuration
    template:
      dest: /etc/sensu/conf.d/api.json
      owner: sensu
      group: sensu
      src: sensu-api.json.j2
    notify: restart sensu-api service

  - name: Ensure Sensu server service is running
    service: name=sensu-server state=started enabled=yes

  - name: Ensure Sensu API service is running
    service: name=sensu-api state=started enabled=yes

  - name: Deploy Sensu client service configuration
    template:
      dest: /etc/sensu/conf.d/client.json
      owner: sensu
      group: sensu
      src: client.json.j2
    notify: restart sensu-client service

  - name: Ensure Sensu client service is running
    service:
      name: sensu-client
      state: started
      enabled: yes