---
  - hosts: jenkins
    become: true
    roles:
      - geerlingguy.java

  - hosts: jenkins_master
    become: yes
    vars:
      jenkins_hostname: 10.0.10.20
      jenkins_http_port: 8000
      jenkins_plugins:
        - ssh-slaves
        - workflow-aggregator
        - git
        - slack
        - junit
      jenkins_plugins_state: present
    roles:
      - geerlingguy.jenkins
      - jenkins_master

  - hosts: jenkins_slaves
    become: yes
    roles:
      - jenkins_slave
