---
  - hosts: jenkins
    become: true
    roles:
      - jenkins_owner
      - geerlingguy.java

  - hosts: jenkins_master
    vars:
      jenkins_hostname: 10.0.10.20
      jenkins_http_port: 8000
    roles:
      - geerlingguy.jenkins
      - jenkins_master_config