---
  # Installs Java and Docker
  - hosts: jenkins
    become: true
    vars:
      docker_install_compose: true
    roles:
      - geerlingguy.java
      - geerlingguy.docker

  # Installs Jenkins and configure it with plugins and Jenkins user
  - hosts: jenkins_master
    become: yes
    vars:
      jenkins_hostname: 10.0.10.20
      jenkins_http_port: 8000
      jenkins_plugins:
        - ssh-slave
        - git
        - slack
        - junit
        - workflow-aggregator
        - performance
    roles:
      - geerlingguy.jenkins
      - jenkins_master

  # Creates and modifies jenkins user to work with Docker
  - hosts: jenkins
    become: true
    roles:
      - users

  # Prepares jenkins slaves
  - hosts: jenkins_slaves
    become: yes
    roles:
      - jenkins_slave

  # Prepares integration slave with needed software
  - hosts: integration_slave
    become: yes
    roles:
      - geerlingguy.nodejs
      - newman
