# Jenkins Master Role
- name: geerlingguy.jenkins
  src: geerlingguy.jenkins

# Java 
- name: geerlingguy.java
  src: geerlingguy.java

# Docker
- name: franklinkim.docker
  src: franklinkim.docker

# Docker Compose
- name: franklinkim.docker-compose
  src: franklinkim.docker-compose