# Jenkins Master Role
- name: jenkins_master
  src: https://github.com/jtyr/ansible-jenkins_master

# Jenkins Slave Role
- name: jenkins_slave
  src: https://github.com/jtyr/ansible-jenkins_slave

- name: config_encoder_filters
  src: https://github.com/jtyr/ansible-config_encoder_filters