# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.provider 'virtualbox' do |vb|
  	vb.customize ['modifyvm', :id, '--cableconnected1', 'on']
    end

    # Ansible Management Machine
    config.vm.define :mgmt do |mgmt|
        mgmt.vm.box = "bento/ubuntu-16.04"
        mgmt.vm.network :private_network, ip: "10.0.10.10"
        mgmt.vm.provider "virtualbox" do |vb|
            vb.memory = "512"
        end

        config.vm.provision "shell", privileged: true, inline: <<-SHELL
          apt-get update
          apt-get -y upgrade
          apt-get -y install software-properties-common
          apt-add-repository -y ppa:ansible/ansible
          apt-get update
          apt-get -y install ansible
          chown -R vagrant:vagrant /vagrant
          echo cd /vagrant >> .bashrc

          apt-get install -y python-pip
          pip install shade
        SHELL


        config.vm.provision "shell", privileged: true, inline: <<-SHELL
            PROD_URI="194.47.174.58"
            PROD_USER="ubuntu"

            # Generate SSH keys used by git
            ssh-keygen -t rsa -f ~/.ssh/confman_id_rsa -q -N ""

            # Copy private key to production server
            # Password: <secret>
            ssh-copy-id -i ~/.ssh/confman_id_rsa -o StrictHostKeyChecking=no $PROD_USER@$PROD_URI

            # Add the production repo
            git remote add production ssh://$PROD_USER@$PROD_URI/opt/confman
        SHELL
    end
end
