// Something to get us started, perhaps dockerize to separate namespaces
// TODO: Correct use of curl
// TODO: More variables

// param giturl: url to student repo on github
// param testsurl: url to additional tests from faculty
// param studentid: API must provide a studenid (to match this build with a student, to be able to report back to API)

node {
    
      // Clone tests from faculty
    dir('./facultytests') {
        stage('Checkout faculty tests') {
            echo "Checking out tests from faculty"
            git credentialsId: 'github-credentials', url: "https://github.com/tommykronstal/getadockerfile"
        }
    }


    // Clone student repo
    dir('student') {
        stage('Checkout student code') {
            try {
                echo "Checking out code from ${giturl}"
                git credentialsId: 'github-credentials', url: "${giturl}"
            } catch(e) {
                // Could not clone student repo, must do something. Report to API or Slack?
            }
        }
    }
        
    // Copy all tests.js-files to student repo
    sh 'cp ./facultytests/*.tests.js ./student/test/'
    sh 'cp ./facultytests/Dockerfile ./student'
        
    stage('Running tests') {
        dir('./student') {
            try {
                sh 'docker build -t tommykronstal/studentapp .'
                sh 'docker run tommykronstal/studentapp'
                // Report exam true. Do we include studentid here?
                //sh 'curl -d "buildOk=true" -H "Content-Type: application/x-www-form-urlencoded" -X POST http://10.0.10.99:8080/reportexam'
            } catch(e) {
                currentBuild.result = 'FAILURE'
                sh "echo 'your tests failed, i will notify your master'"
                // Report exam false. Do we include studentid here?
                //sh 'curl -d "buildOk=false" -H "Content-Type: application/x-www-form-urlencoded" -X POST http://10.0.10.99:8080/reportexam'
            }
        }
    }
}