---
  - name: Create postgresbackup directory
    file:
      path: /opt/postgresbackup
      state: directory

  - name: Copy postgresbackup.conf
    template:
      src: postgresbackup.conf.j2
      dest: /opt/postgresbackup/postgresbackup.conf

  - name: Copy postgresbackup.sh
    copy:
      src: postgresbackup.sh
      dest: /opt/postgresbackup/
      mode: 0777

  #- name: Set cron job
    #cron:
      #name: postgres backup
      #special_time: daily
      #job: bash /opt/postgresbackup/postgresbackup.sh
