---
  - name: Download latest release of Fat Man from Github
    get_url:
      url: https://github.com/acme-config-management/fat-man/releases/download/v{{ version }}/fat-man-{{ version }}-fat.jar
      dest: "{{ install_path }}"
      mode: 0744

  - name: Add Fatman service file to server
    template:
      src: "{{ role_path }}/templates/fatman.service.j2"
      dest: /etc/systemd/system/fatman.service

  - name: Start fatman service
    systemd:
      name: fatman.service
      state: started
      daemon_reload: yes

  - name: Add environment variables
    shell: echo export {{ item }} >> .bashrc
    with_items:
      - "db_ip={{ hostvars['db_service_b']['ansible_host'] }}"
      - "db_port={{ db_port }}"
      - "db_name={{ db_name }}"
      - "db_user={{ db_user }}"
      - "db_pass={{ db_pass }}"
