---
  - name: Download latest release of Fat Man from Github
    get_url:
      url: https://github.com/acme-config-management/fat-man/releases/download/v{{ version }}/fat-man-{{ version }}-fat.jar
      dest: /opt
      mode: 0744
