version: '2'

services:
  web:
    command: pm2-docker index.js
    image: tommykronstal/2dv611api:unstable
    ports:
      - "80:8080"
    links:
      - mongo
    environment:
      - MONGO_DB_URI=mongodb://mongo:27017/slackapp
      - SLACKTOKEN=pHrBUBELk3whs5w1Fsu6fqtJ
      - URL=http://194.47.174.54:80
      - NODE_ENV=production
      - SLACK_API_URL=https://slack.com/api/users.info
      - SLACK_API_TOKEN=xoxp-273720381861-273503337875-295792058871-3b163bd86f0376bb62cf609f4df26983

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes_from:
      - mongodata

  mongodata:
    image: tianon/true
    volumes:
      - /data/mongodb:/data/db