version: '2'

services:
  web:
    #command: npm start
    image: tommykronstal/2dv611api
    ports:
      - "8080:8080"
    links:
      - mongo
    environment:
      - MONGO_DB_URI=mongodb://mongo:27017/slackapp
      - URL=http://82e43bfc.ngrok.io
      - SLACKTOKEN=pHrBUBELk3whs5w1Fsu6fqtJ

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes_from:
      - mongodata

  mongodata:
    image: tianon/true
    volumes:
      - /data/db

  testrunner:
    image: blazemeter/taurus
    command: test.yml jmeter.yml
    volumes:
     - ./test/staging_tests:/bzt-configs
    depends_on:
     - web
    links:
     - web:web