version: '2'

services:
  web:
    #command: npm start
    build: .
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    links:
      - mongo
    command: nodemon -L index.js
    environment:
      - MONGO_DB_URI=mongodb://mongo:27017/slackapp
      - URL=http://d45ea788.ngrok.io
      - SLACKTOKEN=pHrBUBELk3whs5w1Fsu6fqtJ

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes_from:
      - mongodata

  mongodata:
    image: tianon/true
    volumes:
      - /data/db
