version: '2'

services:
  web:
    command: pm2-docker index.js
    image: tommykronstal/2dv611api
    ports:
      - "80:8080"
    links:
      - mongo
    environment:
      - MONGO_DB_URI=mongodb://mongo:27017/slackapp
      - SLACKTOKEN=pHrBUBELk3whs5w1Fsu6fqtJ
      - URL=http://194.47.174.54:80
      - NODE_ENV=production

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes_from:
      - mongodata

  mongodata:
    image: tianon/true
    volumes:
      - /data/db